# eureka server port
server:
  port: 8761

# MSA module id (eureka)
spring:
  application:
    name: discovery-service

# Eureka server does not need to be included
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  # instance:
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

